/* tslint:disable */
// generated by typescript-json-validator
import { inspect } from "util";
import Ajv from "ajv";
import InfluencerSchema from "./influencer.schema";
export const ajv = new Ajv({
  allErrors: true,
  coerceTypes: false,
  format: "fast",
  nullable: true,
  unicode: true,
  uniqueItems: true,
  useDefaults: true,
});


ajv.addMetaSchema(require("ajv/lib/refs/json-schema-draft-06.json"));

export { InfluencerSchema };
export const InfluencerSchemaSchema = {
  $schema: "http://json-schema.org/draft-07/schema#",
  defaultProperties: [],
  properties: {
    description: {
      type: "string",
    },
    facebook_username: {
      type: "string",
    },
    instagram_username: {
      type: "string",
    },
    name: {
      minLength: 1,
      type: "string",
    },
    twitter_username: {
      type: "string",
    },
    youtube_username: {
      type: "string",
    },
  },
  required: ["name"],
  type: "object",
  anyRequired: ["foo", "bar"],
};
export type ValidateFunction<T> = ((data: unknown) => data is T) &
  Pick<Ajv.ValidateFunction, "errors">;
export const isInfluencerSchema = ajv.compile(
  InfluencerSchemaSchema
) as ValidateFunction<InfluencerSchema>;
export default function validate(value: unknown): InfluencerSchema {
  if (isInfluencerSchema(value)) {
    return value;
  } else {
    throw new Error(
      ajv.errorsText(
        isInfluencerSchema.errors!.filter((e: any) => e.keyword !== "if"),
        { dataVar: "InfluencerSchema" }
      ) +
        "\n\n" +
        inspect(value)
    );
  }
}
